apiVersion: v1
kind: ServiceAccount
metadata:
  name: identity-sa
  namespace: essay-genius

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-role
  namespace: essay-genius
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: essay-genius
subjects:
  - kind: ServiceAccount
    name: identity-sa
    namespace: essay-genius
roleRef:
  kind: Role
  name: pod-reader-role
  apiGroup: rbac.authorization.k8s.io
