services:
  # POSTGRES
  eg-identity-service-postgres:
    image: postgres:${SOFTWARE_VERSION_TAG}
    container_name: eg-identity-service-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eternity_user
      POSTGRES_PASSWORD: a_will_eternal
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: identity_service_db
    volumes:
      - eg-identity-service-postgres-data:/var/lib/postgresql/data
      - ./postgres/identity-service-postgres-init-db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - eg-network

  # PGADMIN
  eg-identity-service-pgadmin:
    image: elestio/pgadmin:latest
    container_name: eg-identity-service-pgadmin
    depends_on: [eg-identity-service-postgres]
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    volumes:
      - eg-identity-service-pgadmin-data:/var/lib/pgadmin
    networks:
      - eg-network

  #  REDIS
  eg-identity-service-redis:
    image: redis:latest
    container_name: eg-identity-service-redis
    volumes:
      - eg-identity-service-redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - eg-network
    restart: unless-stopped

  # KAFKA BROKER
  eg-kafka-broker:
    image: apache/kafka:4.0.1
    container_name: eg-kafka-broker
    environment:
      # KRaft mode
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@eg-kafka-broker:9093
      # Listeners
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      # Optional: allow auto topic creation if needed
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    volumes:
      - ./docker/kafka/certs:/bitnami/kafka/config/certs # If have certs
      - eg-kafka-broker-data:/var/lib/kafka/data
    ports:
      - "9094:9092"
    networks:
      - eg-network
    restart: unless-stopped

  #  MONGODB
  eg-essay-service-mongodb:
    image: mongo:latest
    container_name: eg-essay-service-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: eternity_user
      MONGO_INITDB_ROOT_PASSWORD: a_will_eternal
    volumes:
      - eg-essay-service-mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - eg-network
    restart: unless-stopped

  # MONGODB EXPRESS
  eg-essay-service-mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    container_name: eg-essay-service-mongo-express
    depends_on: [eg-essay-service-mongodb]
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: eternity_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: a_will_eternal
      ME_CONFIG_MONGODB_SERVER: essay-service-mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
    ports:
      - "5051:8081"
    networks:
      - eg-network
    restart: unless-stopped

  eg-interaction-service-mongodb:
    image: mongo:latest
    container_name: eg-interaction-service-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: eternity_user
      MONGO_INITDB_ROOT_PASSWORD: a_will_eternal
    volumes:
      - eg-interaction-service-mongodb-data:/data/db
    ports:
      - "27019:27017"
    networks:
      - eg-network
    restart: unless-stopped

  eg-minio:
    image: minio/minio:RELEASE.2024-08-17T01-24-54Z.fips
    container_name: eg-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - eg-minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped

  #LOKI
  eg-loki:
    image: grafana/loki:2.9.6
    container_name: eg-loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    networks:
      - eg-network
    restart: unless-stopped

  #  PROMETHEUS
  eg-prometheus:
    image: prom/prometheus:main
    container_name: eg-prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/grafana-stack/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - eg-network
    restart: unless-stopped

  #  TEMPO
  eg-tempo:
    image: grafana/tempo:main-bbe0435
    container_name: eg-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./docker/grafana-stack/tempo/tempo.yml:/etc/tempo.yaml:ro
      - ./docker/grafana-stack/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100" # Tempo
      - "9411:9411" # zipkin
      - "4317:4317" # OTel
    networks:
      - eg-network
    restart: unless-stopped

  #  GRAFANA
  eg-grafana:
    image: grafana/grafana:10.1.0
    container_name: eg-grafana
    environment:
      #      GF_AUTH_ANONYMOUS_ENABLED: true
      #      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
      #      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_SECURITY_ADMIN_USER: eternity_user
      GF_SECURITY_ADMIN_PASSWORD: a_will_eternal
    volumes:
      #      - ./docker/grafana-stack/grafana:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana-stack/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./docker/grafana-stack/grafana/dashboards:/etc/grafana/provisioning/dashboards
      #      - ./docker/grafana-stack/grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "3000:3000"
    networks:
      - eg-network
    restart: unless-stopped

networks:
  eg-network:
    driver: bridge

volumes:
  eg-identity-service-postgres-data:
  eg-identity-service-pgadmin-data:
  eg-identity-service-redis-data:
  eg-kafka-broker-data:
  eg-essay-service-mongodb-data:
  eg-interaction-service-mongodb-data:
  eg-minio-data:

