apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-frontend
  namespace: essay-genius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-frontend
  template:
    metadata:
      labels:
        app: eg-frontend
    spec:
      containers:
        - name: eg-frontend
          image: ntphat30019/essay-genius-fe:v4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: eg-frontend
  namespace: essay-genius
spec:
  type: ClusterIP
  selector:
    app: eg-frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
