global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['eg-prometheus:9090']

  - job_name: 'Gateway'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:9050']

  - job_name: 'IdentityService'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['localhost:10000']

  - job_name: 'EssayService'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:10002' ]

  - job_name: 'InteractionService'
    scrape_interval: 2s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'localhost:10003' ]