server:
  port: 9050
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: Identity Service
        url: /identity/v3/api-docs
      - name: Essay Service
        url: /essay/v3/api-docs
      - name: Interaction Service
        url: /interaction/v3/api-docs
  api-docs:
    enabled: true
    path: /v3/api-docs

spring:
  config:
    import:
      - "optional:file:env.properties"
      - "optional:file:../env.properties"
  application:
    name: gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOrigins: ${ESSAY_GENIUS_URL}
            allowedMethods: "*"
            allowedHeaders: "Authorization,Content-Type,Accept-Language,No-Auth"
            allowCredentials: true
      routes:
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
        - id: essay-service
          uri: lb://ESSAY-SERVICE
          predicates:
            - Path=/essay,/essay/**
        - id: interaction-service
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/interaction,/interaction/**

#      routes:
#        - id: identity-service
#          uri: ${IDENTITY_SERVICE_URL}
#          predicates:
#            - Path=/identity/**
#
#        - id: essay-service
#          uri: ${ESSAY_SERVICE_URL}
#          predicates:
#            - Path=/essay/**
#
#        - id: interaction-service
#          uri: ${INTERACTION_SERVICE_URL}
#          predicates:
#            - Path=/interaction,/interaction/**
  main:
    web-application-type: reactive

  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en
    cache-duration: 3600

#logging:
#  level:
#    org.springframework.beans.factory: DEBUG
#    org.springframework.cloud.gateway: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false

#_______________________________________MANAGEMENT_______________________________________
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
  endpoint:
    health:
      show-details: always

  info:
    git:
      enabled: true
      mode: full

  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
    tags:
      application: ${spring.application.name}

  observations:
    key-values:
      application: ${spring.application.name}

  tracing:
    enabled: true
    sampling:
      probability: 1.0

loki:
  url: ${LOKI_URL:http://localhost:3100/loki/api/v1/push}
