apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: eg-ingress
  namespace: essay-genius
spec:
  ingressClassName: nginx
  rules:
    - host: essay-genius.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eg-frontend
                port:
                  number: 80

    - host: api.essay-genius.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: eg-gateway
                port:
                  number: 9050
