apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
  namespace: essay-genius
data:
  LOKI_URL: "http://eg-loki.essay-genius.svc.cluster.local:3100/loki/api/v1/push"
  IDENTITY_SERVICE_URL: "http://eg-identity-service.essay-genius.svc.cluster.local:10000"
  ESSAY_SERVICE_URL: "http://eg-essay-service.essay-genius.svc.cluster.local:10002"
  INTERACTION_SERVICE_URL: "http://eg-interaction-service.essay-genius.svc.cluster.local:10003"
  GATEWAY_PUBLIC_URL: "http://localhost:9050"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://tempo:9411"
