apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eg-interaction-mongodb
  namespace: essay-genius
spec:
  serviceName: eg-interaction-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: eg-interaction-mongodb
  template:
    metadata:
      labels:
        app: eg-interaction-mongodb
    spec:
      containers:
        - name: eg-interaction-mongodb
          image: mongo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_PASSWORD
          volumeMounts:
            - name: interaction-data
              mountPath: /data/db
      volumes:
        - name: interaction-data
          persistentVolumeClaim:
            claimName: eg-interaction-mongodb-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: eg-interaction-mongodb
  namespace: essay-genius
  labels:
    app: eg-interactoin-mongodb
spec:
  ports:
    - name: 27017-27017
      protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: eg-interaction-mongodb
  type: ClusterIP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eg-interaction-mongodb-pvc
  namespace: essay-genius
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
