apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eg-kafka
  namespace: essay-genius
spec:
  serviceName: eg-kafka
  replicas: 1
  selector:
    matchLabels:
      app: eg-kafka
  template:
    metadata:
      labels:
        app: eg-kafka
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: eg-kafka
          image: apache/kafka:4.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 29092
              name: plaintext
            - containerPort: 29093
              name: controller
            - containerPort: 9092
              name: plaintext-host
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            # KRaft
            - name: KAFKA_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: "1@eg-kafka-0.eg-kafka.essay-genius.svc.cluster.local:29093"

            # Listeners
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092"

            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://eg-kafka-0.eg-kafka.essay-genius.svc.cluster.local:29092,PLAINTEXT_HOST://$(NODE_IP):9092"

            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"

            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "PLAINTEXT"

            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"

            # Replication config
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: "0"
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: "1"
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: "1"

            - name: KAFKA_LOG_DIRS
              value: "/var/lib/kafka/data"

          volumeMounts:
            - name: kafka-data
              mountPath: /var/lib/kafka/data

  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: eg-kafka
  namespace: essay-genius
spec:
  clusterIP: None
  selector:
    app: eg-kafka
  ports:
    - name: plaintext
      port: 29092
      targetPort: 29092
    - name: controller
      port: 29093
      targetPort: 29093
