apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-mongo-express
  namespace: essay-genius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-mongo-express
  template:
    metadata:
      labels:
        app: eg-mongo-express
    spec:
      initContainers:
        - name: wait-for-mongodb
          image: mongo:latest
          imagePullPolicy: Never
          command:
            - sh
            - -c
            - |
              until mongosh "mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@eg-essay-mongodb:27017/admin" \
                --eval "db.adminCommand('ping')" >/dev/null 2>&1; do
                echo "Waiting for Essay MongoDB...";
                sleep 2;
              done
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_PASSWORD
      containers:
        - name: mongo-express
          image: mongo-express:1.0.2-20-alpine3.19
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ENABLE_ADMIN
              value: "true"

            # default connection (essay)
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_USERNAME

            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: eg-mongodb-admin-secrets
                  key: MONGODB_PASSWORD

            - name: ME_CONFIG_MONGODB_SERVER
              value: eg-essay-mongodb

            # login mongo-express
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eg-mongo-express-secrets
                  key: ME_USERNAME

            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eg-mongo-express-secrets
                  key: ME_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: eg-mongo-express
  namespace: essay-genius
spec:
  type: ClusterIP
  selector:
    app: eg-mongo-express
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: v1
kind: Secret
metadata:
  name: eg-mongo-express-secrets
  namespace: essay-genius
type: Opaque
data:
  ME_USERNAME: cm9vdA==
  ME_PASSWORD: cm9vdA==
