apiVersion: apps/v1
kind: Deployment
metadata:
  name: eg-minio
  namespace: essay-genius
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eg-minio
  template:
    metadata:
      labels:
        app: eg-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:RELEASE.2024-08-17T01-24-54Z.fips
          imagePullPolicy: Never
          args:
            - server
            - /data
            - "--console-address"
            - ":9001"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          envFrom:
            - secretRef:
                name: eg-minio-secrets
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: eg-minio-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: eg-minio
  namespace: essay-genius
spec:
  type: ClusterIP
  selector:
    app: eg-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001

---
apiVersion: v1
kind: Secret
metadata:
  name: eg-minio-secrets
  namespace: essay-genius
type: Opaque
stringData:
  MINIO_ROOT_USER: minioadmin
  MINIO_ROOT_PASSWORD: minioadmin

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eg-minio-pvc
  namespace: essay-genius
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
