apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eg-prometheus
  namespace: essay-genius
spec:
  serviceName: eg-prometheus
  replicas: 1
  selector:
    matchLabels:
      app: eg-prometheus
  template:
    metadata:
      labels:
        app: eg-prometheus
    spec:
      initContainers:
        - name: grant-permission
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              mkdir -p /prometheus &&\
              chown -R 65534:65534 /prometheus
          volumeMounts:
            - name: prometheus-data
              mountPath: /prometheus
      containers:
        - name: prometheus
          image: prom/prometheus:main
          imagePullPolicy: IfNotPresent
          args:
            - --enable-feature=exemplar-storage
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
            - name: prometheus-data
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: eg-prometheus-config
  volumeClaimTemplates:
    - metadata:
        name: prometheus-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: eg-prometheus
  namespace: essay-genius
spec:
  selector:
    app: eg-prometheus
  ports:
    - port: 9090
      targetPort: 9090
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eg-prometheus-config
  namespace: essay-genius
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['eg-prometheus:9090']
    
      - job_name: 'gateway'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eg-gateway.essay-genius.svc.cluster.local:9050']
            labels:
              application: "gateway"
    
      - job_name: 'identityservice'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eg-identity-service.essay-genius.svc.cluster.local:10000']
            labels:
              application: "identity service"
    
      - job_name: 'essayservice'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eg-essay-service.essay-genius.svc.cluster.local:10002']
            labels:
              application: "essay service"
    
      - job_name: 'interactionservice'
        scrape_interval: 2s
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['eg-interaction-service.essay-genius.svc.cluster.local:10003']
            labels:
              application: "interaction service"