apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eg-tempo
  namespace: essay-genius
spec:
  serviceName: eg-tempo
  replicas: 1
  selector:
    matchLabels:
      app: eg-tempo
  template:
    metadata:
      labels:
        app: eg-tempo
    spec:
      containers:
        - name: tempo
          image: grafana/tempo:main-bbe0435
          imagePullPolicy: IfNotPresent
          args:
            - -config.file=/etc/tempo/tempo.yaml
          ports:
            - containerPort: 3100
            - containerPort: 9411
            - containerPort: 4317
          volumeMounts:
            - name: tempo-config
              mountPath: /etc/tempo
            - name: tempo-data
              mountPath: /tmp/tempo
      volumes:
        - name: tempo-config
          configMap:
            name: eg-tempo-config
  volumeClaimTemplates:
    - metadata:
        name: tempo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 3Gi

---
apiVersion: v1
kind: Service
metadata:
  name: eg-tempo
  namespace: essay-genius
spec:
  selector:
    app: eg-tempo
  ports:
    - name: tempo
      port: 3100
    - name: zipkin
      port: 9411
    - name: otlp
      port: 4317
  type: ClusterIP

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: eg-tempo-config
  namespace: essay-genius
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    distributor:
      receivers:
        zipkin:
        otlp:
          protocols:
            grpc:
            http:

    ingester:
      trace_idle_period: 10s
      max_block_bytes: 1_000_000
      max_block_duration: 5m

    compactor:
      compaction:
        block_retention: 24h

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo/traces
